name: Serialization Library Release

on: workflow_dispatch
      
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: dotnet restore Amazon.QLDB.Driver.Serialization.sln
      - name: Build
        run: dotnet build Amazon.QLDB.Driver.Serialization.sln --configuration Release --no-restore
      - name: Unit Test
        run: dotnet test Amazon.QLDB.Driver.Serialization.Tests

  release:
    name: Release
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] 
        dotnet: ['3.1.x']
      
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SIGNING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SIGNING }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 900
          
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.1
      - name: Git Checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
        
      - name: Sign
        run: |
          dotnet build Amazon.QLDB.Driver.Serialization.sln --configuration Release
          
          # Push unsigned DLL to S3
          version_id=$( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_SERIALIZATION }} --body Amazon.QLDB.Driver.Serialization/bin/Release/netcoreapp3.1/Amazon.QLDB.Driver.Serialization.dll  --acl bucket-owner-full-control | jq '.VersionId' )
          
          job_id=""
          
          # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
          # Will sleep for 5 seconds between retries.
          for (( i=0; i<3; i++ ))
          do  
            # Get job ID
            id=$( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_SERIALIZATION }} --version-id ${version_id} | jq -r '.TagSet[0].Value' )
            if [ $id != "null" ]
            then
              job_id=$id
              break
            fi
            
            sleep 5s
          done
          
          if [[ $job_id = "" ]]
          then
             echo "Exiting because unable to retrieve job ID"
             exit 1
          fi

          # Poll signed S3 bucket to see if the signed artifact is there
          aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_SERIALIZATION }}-${job_id}
          
          # Get signed DLL from S3
          aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_SERIALIZATION }}-${job_id} Amazon.QLDB.Driver.Serialization/bin/Release/netcoreapp3.1/Amazon.QLDB.Driver.Serialization.dll

      - name: Publish to NuGet
        run: |
          dotnet pack Amazon.QLDB.Driver.Serialization.sln --configuration Release --no-build
          dotnet nuget push Amazon.QLDB.Driver.Serialization/bin/Release/Amazon.QLDB.Driver.Serialization.*.nupkg --api-key ${{ secrets.AWS_NUGET_KEY }} --source https://api.nuget.org/v3/index.json
